# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4c0afbb26a7f504a957ab581b8c6c1fb113a6636a0110302b9862005c20870abee6c6be4326dc7bac3d96d582cf4531443c914b3254abef1cd7fd9ff7f36251

test:
  secret_key_base: a33cd018f6c562ad3ccd9d86e9cde2537ae48cc95f864653e1eb3e65aefaf131b9d8ad692c94f2044dc2a678a0a6cae84e995bf11d959ab3e7d4bd4a084fa20f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
